import { DiveSite } from "@shared/schema";

// This file contains sample dive site data used for testing and development
// In a production environment, this data would come from the backend API

export const sampleDiveSites: DiveSite[] = [
  {
    id: 1,
    name: "Great Barrier Reef",
    description: "The Great Barrier Reef is the world's largest coral reef system, stretching over 2,300 kilometers along the coast of Queensland, Australia. It offers some of the most spectacular diving experiences with its vibrant coral formations and diverse marine life.",
    location: "Queensland, Australia",
    country: "Australia",
    latitude: -16.7525,
    longitude: 146.5361,
    difficulty: "Intermediate",
    minDepth: 15,
    maxDepth: 30,
    minVisibility: 10,
    maxVisibility: 30,
    minTemp: 24,
    maxTemp: 30,
    current: "Mild",
    bestSeason: "June - November",
    peakVisibilityMonth: "September",
    conservationStatus: "Protected Area",
    conservationInfo: "The Great Barrier Reef is a UNESCO World Heritage site facing threats from climate change, water pollution, and coastal development. Visitors are required to follow strict guidelines to minimize impact.",
    mainImage: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    highlights: ["Coral Gardens", "Reef Sharks", "Sea Turtles", "Manta Rays", "Wreck Diving", "Night Dives"],
    habitats: ["Coral Gardens", "Drop-offs", "Sandy Flats", "Sea Grass Beds"],
  },
  {
    id: 2,
    name: "Blue Hole",
    description: "The Blue Hole in Belize is a world-renowned dive site that is part of the Lighthouse Reef System. This perfectly circular underwater sinkhole is over 300 meters across and 125 meters deep, offering divers a chance to see incredible marine life and geological formations.",
    location: "Lighthouse Reef Atoll, Belize",
    country: "Belize",
    latitude: 17.3158,
    longitude: -87.5358,
    difficulty: "Advanced",
    minDepth: 5,
    maxDepth: 40,
    minVisibility: 15,
    maxVisibility: 40,
    minTemp: 26,
    maxTemp: 29,
    current: "Moderate",
    bestSeason: "April - June",
    peakVisibilityMonth: "May",
    conservationStatus: "Marine Reserve",
    conservationInfo: "Part of the Belize Barrier Reef Reserve System, a UNESCO World Heritage site requiring careful conservation efforts to protect its unique ecosystem.",
    mainImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    highlights: ["Deep Blue Waters", "Stalactites", "Sharks", "Coral Formations", "Clear Visibility"],
    habitats: ["Sinkhole", "Reef Wall", "Open Ocean"],
  },
  {
    id: 3,
    name: "Tubbataha Reefs",
    description: "The Tubbataha Reefs Natural Park is a remote diving destination in the Sulu Sea, Philippines. This protected marine sanctuary features extraordinary biodiversity with pristine coral reefs and an abundance of marine life.",
    location: "Sulu Sea, Philippines",
    country: "Philippines",
    latitude: 8.8011,
    longitude: 119.8902,
    difficulty: "Advanced",
    minDepth: 10,
    maxDepth: 40,
    minVisibility: 20,
    maxVisibility: 45,
    minTemp: 26,
    maxTemp: 30,
    current: "Strong",
    bestSeason: "March - June",
    peakVisibilityMonth: "April",
    conservationStatus: "UNESCO World Heritage Site",
    conservationInfo: "Strictly protected marine sanctuary with limited visitor access to preserve its unique marine ecosystem.",
    mainImage: "https://images.unsplash.com/photo-1533713692156-f70938dc0d54?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    highlights: ["Pristine Corals", "Sharks", "Manta Rays", "Sea Turtles", "Wall Diving"],
    habitats: ["Coral Reef", "Reef Wall", "Atolls"],
  }
];

export default sampleDiveSites;
