import React, { useState } from "react";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Progress } from "@/components/ui/progress";
import { LessonCard } from "@/components/learn/LessonCard";
import { QuizCard } from "@/components/learn/QuizCard";
import { BadgeDisplay } from "@/components/learn/BadgeDisplay";
import { InteractiveLessonCard } from "@/components/learn/InteractiveLessonCard";

import { Compass, BookOpen, Fish, Award, ChevronLeft, ChevronRight, Waves, Thermometer, MapPin } from "lucide-react";

const categories = [
  { id: "ocean-literacy", name: "Ocean Literacy", icon: <Compass className="h-5 w-5" /> },
  { id: "reef-ecology", name: "Reef Ecology", icon: <BookOpen className="h-5 w-5" /> },
  { id: "species-identification", name: "Species ID", icon: <Fish className="h-5 w-5" /> },
];

// Sample lessons data
const lessons = [
  {
    id: 1,
    title: "Introduction to Coral Reefs",
    category: "reef-ecology",
    duration: 5,
    thumbnail: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Learn about the formation and importance of coral reefs in marine ecosystems.",
    completed: false,
    content: [
      {
        type: "text",
        data: "Coral reefs are underwater ecosystems characterized by reef-building corals. Reefs are formed of colonies of coral polyps held together by calcium carbonate. Most coral reefs are built from stony corals, whose polyps cluster in groups."
      },
      {
        type: "image",
        data: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        caption: "Vibrant coral reef with diverse marine life"
      },
      {
        type: "text",
        data: "Coral reefs are among the most diverse ecosystems on Earth, housing thousands of species of marine life. They provide habitat, breeding grounds, and protection for countless marine organisms."
      },
      {
        type: "funFact",
        data: "Although coral reefs cover less than 1% of the ocean floor, they support about 25% of all marine species!"
      }
    ]
  },
  {
    id: 2,
    title: "Understanding Ocean Currents",
    category: "ocean-literacy",
    duration: 3,
    thumbnail: "https://images.unsplash.com/photo-1566024287286-457247b70310?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Discover how ocean currents shape marine environments and global climate.",
    completed: false,
    content: [
      {
        type: "text",
        data: "Ocean currents are continuous, directed movements of seawater generated by a number of forces acting upon the water, including wind, the Coriolis effect, temperature and salinity differences."
      },
      {
        type: "image",
        data: "https://images.unsplash.com/photo-1566024287286-457247b70310?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        caption: "Ocean surface showing current patterns"
      },
      {
        type: "text",
        data: "Surface currents are primarily driven by winds. Deep ocean currents are driven by differences in water density, caused by variations in temperature and salinity - a process known as thermohaline circulation."
      },
      {
        type: "funFact",
        data: "The Gulf Stream transports nearly 4 billion cubic feet of water per second, which is more than 300 times the flow of the Amazon River!"
      }
    ]
  },
  {
    id: 3,
    title: "Identifying Reef Fish",
    category: "species-identification",
    duration: 4,
    thumbnail: "https://images.unsplash.com/photo-1545759332-b3a0e9a1c59b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Learn to identify common reef fish families and species during your dives.",
    completed: true,
    content: [
      {
        type: "text",
        data: "Being able to identify fish enhances your diving experience and contributes to citizen science. Fish identification starts with recognizing key features: body shape, size, coloration patterns, fin shape and placement."
      },
      {
        type: "image",
        data: "https://images.unsplash.com/photo-1545759332-b3a0e9a1c59b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        caption: "Variety of colorful reef fish"
      },
      {
        type: "text",
        data: "Common reef fish families include Butterflyfish (Chaetodontidae), Angelfish (Pomacanthidae), Parrotfish (Scaridae), and Wrasses (Labridae). Each has distinctive characteristics that help with identification."
      },
      {
        type: "funFact",
        data: "Many reef fish can change their sex during their lifetime! This adaptation, called sequential hermaphroditism, allows for optimal reproductive strategies."
      }
    ]
  },
  {
    id: 4,
    title: "Marine Conservation Basics",
    category: "ocean-literacy",
    duration: 5,
    thumbnail: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Understand key principles and practices in marine conservation.",
    completed: false,
    content: [
      {
        type: "text",
        data: "Marine conservation focuses on protecting and preserving marine ecosystems, habitats, and species from damage and degradation. It involves establishing marine protected areas, sustainable fishing practices, and reducing pollution."
      },
      {
        type: "image",
        data: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        caption: "Marine conservation efforts in action"
      },
      {
        type: "text",
        data: "As a diver, you can contribute to marine conservation by practicing responsible diving, participating in debris cleanup, and reporting unusual observations to conservation organizations."
      },
      {
        type: "funFact",
        data: "The world's oceans absorb about 30% of the carbon dioxide that humans release into the atmosphere, helping to mitigate climate change!"
      }
    ]
  },
  {
    id: 5,
    title: "Coral Bleaching Explained",
    category: "reef-ecology",
    duration: 3,
    thumbnail: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Learn about the causes and impacts of coral bleaching on reef ecosystems.",
    completed: false,
    content: [
      {
        type: "text",
        data: "Coral bleaching occurs when corals expel the algae (zooxanthellae) living in their tissues due to stress, causing the coral to turn completely white. The main causes include increased sea temperatures, pollution, and ocean acidification."
      },
      {
        type: "image",
        data: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        caption: "Bleached coral showing white coloration"
      },
      {
        type: "text",
        data: "While bleached corals are not dead, they are under severe stress and are at risk of mortality if conditions don't improve. The loss of coral reefs impacts countless marine species that depend on them for habitat and food."
      },
      {
        type: "funFact",
        data: "Some coral species have shown the ability to adapt to higher temperatures over time, giving hope that certain reefs may become more resilient to climate change!"
      }
    ]
  },
  {
    id: 6,
    title: "The Leeuwin Current",
    category: "ocean-literacy",
    duration: 8,
    thumbnail: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Interactive lesson about Western Australia's unique warm ocean current and its impact on marine life.",
    completed: false,
    isInteractive: true,
    steps: [
      {
        id: 1,
        type: "intro",
        title: "Welcome to the Leeuwin Current",
        content: {
          image: "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
          imageCaption: "The Leeuwin Current flowing along Western Australia",
          text: "The Leeuwin Current is one of the world's most unique ocean currents. Unlike most eastern boundary currents that are cold, the Leeuwin Current is warm, flowing southward along Australia's west coast. This warm current has a huge impact on Western Australia's marine life, bringing tropical species far south and creating some of the world's most diverse temperate reefs."
        }
      },
      {
        id: 2,
        type: "map",
        title: "Where Does the Leeuwin Current Flow?",
        content: {
          facts: [
            {
              icon: <Waves className="h-5 w-5 text-blue-600" />,
              title: "Flow Direction",
              description: "Flows southward from North West Cape to Cape Leeuwin, then eastward"
            },
            {
              icon: <Thermometer className="h-5 w-5 text-red-600" />,
              title: "Temperature",
              description: "Carries warm water 2-5°C warmer than expected for the latitude"
            },
            {
              icon: <Fish className="h-5 w-5 text-green-600" />,
              title: "Marine Life",
              description: "Enables tropical fish to live as far south as Perth and beyond"
            }
          ]
        }
      },
      {
        id: 3,
        type: "quiz",
        title: "Test Your Knowledge",
        content: {
          questions: [
            {
              question: "What makes the Leeuwin Current unique compared to other eastern boundary currents?",
              options: [
                "It flows northward instead of southward",
                "It's a warm current instead of a cold current",
                "It only flows during summer months",
                "It's the fastest ocean current in the world"
              ],
              correctAnswer: 1,
              explanation: "Most eastern boundary currents (like the California Current) are cold, but the Leeuwin Current is warm, making it unique."
            },
            {
              question: "How does the Leeuwin Current affect marine biodiversity in Western Australia?",
              options: [
                "It reduces biodiversity by warming the water",
                "It has no significant impact on marine life",
                "It increases biodiversity by bringing tropical species south",
                "It only affects fish populations, not other marine life"
              ],
              correctAnswer: 2,
              explanation: "The warm Leeuwin Current allows tropical marine species to extend their range much further south than they normally could."
            },
            {
              question: "When is the Leeuwin Current typically strongest?",
              options: [
                "During summer (December-February)",
                "During winter (June-August)",
                "It maintains constant strength year-round",
                "During spring tides only"
              ],
              correctAnswer: 1,
              explanation: "The Leeuwin Current is typically strongest during the Australian winter months when the pressure gradient is greatest."
            }
          ]
        }
      },
      {
        id: 4,
        type: "funFact",
        title: "Amazing Facts About the Leeuwin Current",
        content: {
          fact: "The Leeuwin Current is one of the only warm poleward-flowing currents on the eastern boundary of an ocean basin in the world!",
          moreFacts: [
            "It transports about 5 million cubic meters of water per second - that's more than 1000 times the flow of the Murray River!",
            "The current allows coral reefs to grow as far south as the Houtman Abrolhos Islands, at 29°S latitude.",
            "Some tropical fish species can be found as far south as Albany (35°S) thanks to the Leeuwin Current.",
            "The current varies seasonally, being strongest in winter and weakest in summer, opposite to most currents."
          ]
        }
      }
    ]
  }
];

// Sample quizzes data
const quizzes = [
  {
    id: 1,
    title: "Coral Reef Basics",
    category: "reef-ecology",
    questions: [
      {
        question: "What percentage of the ocean floor do coral reefs cover?",
        options: ["Less than 1%", "About 5%", "About 10%", "More than 20%"],
        correctAnswer: 0
      },
      {
        question: "What are coral polyps?",
        options: [
          "A type of fish that lives in reefs",
          "Tiny soft-bodied organisms related to sea anemones",
          "A type of algae that grows on coral",
          "Rock formations created by ocean currents"
        ],
        correctAnswer: 1
      },
      {
        question: "What is the primary threat to coral reefs globally?",
        options: [
          "Overfishing",
          "Tourism",
          "Climate change",
          "Natural predators"
        ],
        correctAnswer: 2
      }
    ]
  },
  {
    id: 2,
    title: "Marine Species Identification",
    category: "species-identification",
    questions: [
      {
        question: "Which of these is NOT a common reef fish family?",
        options: ["Butterflyfish", "Parrotfish", "Salmonidae", "Wrasses"],
        correctAnswer: 2
      },
      {
        question: "What is the primary distinguishing feature of parrotfish?",
        options: [
          "Bright red coloration",
          "Fused teeth that form a beak-like structure",
          "Long, flowing fins",
          "Ability to change color rapidly"
        ],
        correctAnswer: 1
      },
      {
        question: "Which of these species is known for a symbiotic relationship with sea anemones?",
        options: [
          "Clownfish",
          "Manta ray",
          "Moray eel",
          "Triggerfish"
        ],
        correctAnswer: 0
      }
    ]
  }
];

// Sample badges data
const badges = [
  {
    id: 1,
    name: "Coral Expert",
    description: "Complete all reef ecology lessons",
    icon: <Award className="h-6 w-6 text-yellow-500" />,
    earned: false
  },
  {
    id: 2,
    name: "Quiz Master",
    description: "Score 100% on 5 different quizzes",
    icon: <Award className="h-6 w-6 text-blue-500" />,
    earned: false
  },
  {
    id: 3,
    name: "Species Identifier",
    description: "Complete all species ID lessons",
    icon: <Award className="h-6 w-6 text-green-500" />,
    earned: false
  },
  {
    id: 4,
    name: "Ocean Scholar",
    description: "Complete all ocean literacy lessons",
    icon: <Award className="h-6 w-6 text-purple-500" />,
    earned: false
  },
  {
    id: 5,
    name: "Dive Student",
    description: "Complete your first lesson",
    icon: <Award className="h-6 w-6 text-teal-500" />,
    earned: true
  }
];

export default function LearnPage() {
  const [selectedCategory, setSelectedCategory] = useState(categories[0].id);
  const [viewMode, setViewMode] = useState<"lessons" | "quizzes" | "badges">("lessons");
  const [activeInteractiveLesson, setActiveInteractiveLesson] = useState<any>(null);
  
  // Calculate completion stats
  const totalLessons = lessons.length;
  const completedLessons = lessons.filter(lesson => lesson.completed).length;
  const completionPercentage = Math.round((completedLessons / totalLessons) * 100);
  
  // Filter lessons by category
  const filteredLessons = lessons.filter(lesson => 
    selectedCategory === "all" ? true : lesson.category === selectedCategory
  );
  
  // Filter quizzes by category
  const filteredQuizzes = quizzes.filter(quiz => 
    selectedCategory === "all" ? true : quiz.category === selectedCategory
  );

  const handleLessonClick = (lesson: any) => {
    if (lesson.isInteractive) {
      setActiveInteractiveLesson(lesson);
    }
  };

  // If an interactive lesson is active, show it
  if (activeInteractiveLesson) {
    return (
      <div className="container py-8 mx-auto max-w-7xl">
        <div className="mb-4">
          <Button
            variant="outline"
            onClick={() => setActiveInteractiveLesson(null)}
          >
            <ChevronLeft className="h-4 w-4 mr-2" />
            Back to Lessons
          </Button>
        </div>
        <InteractiveLessonCard lesson={activeInteractiveLesson} />
      </div>
    );
  }

  return (
    <div className="container py-8 mx-auto max-w-7xl">
      <div className="flex flex-col md:flex-row gap-6">
        {/* Sidebar */}
        <div className="w-full md:w-1/4 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>My Progress</CardTitle>
              <CardDescription>
                {completedLessons} of {totalLessons} lessons completed
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Progress value={completionPercentage} className="h-2" />
              
              <div className="mt-6 space-y-2">
                <p className="text-sm font-medium">Learning Categories</p>
                {categories.map(category => (
                  <Button
                    key={category.id}
                    variant={selectedCategory === category.id ? "default" : "outline"}
                    className="w-full justify-start"
                    onClick={() => setSelectedCategory(category.id)}
                  >
                    <span className="mr-2">{category.icon}</span>
                    {category.name}
                  </Button>
                ))}
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader>
              <CardTitle>Suggested For You</CardTitle>
              <CardDescription>
                Based on your recent activity
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="rounded-lg overflow-hidden border">
                <img 
                  src="https://images.unsplash.com/photo-1560275619-4662e36fa65c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80" 
                  alt="Manta ray"
                  className="w-full h-32 object-cover"
                />
                <div className="p-3">
                  <h4 className="font-medium">Manta Ray Identification</h4>
                  <p className="text-sm text-gray-500 mt-1">You logged a manta ray sighting recently</p>
                  <Button variant="link" className="px-0 h-8 mt-1">Learn more</Button>
                </div>
              </div>
              
              <div className="rounded-lg overflow-hidden border">
                <img 
                  src="https://images.unsplash.com/photo-1546026423-cc4642628d2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&q=80" 
                  alt="Great Barrier Reef"
                  className="w-full h-32 object-cover"
                />
                <div className="p-3">
                  <h4 className="font-medium">Great Barrier Reef Ecology</h4>
                  <p className="text-sm text-gray-500 mt-1">Prepare for your upcoming dive</p>
                  <Button variant="link" className="px-0 h-8 mt-1">Learn more</Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
        
        {/* Main content */}
        <div className="w-full md:w-3/4">
          <Card className="mb-6">
            <CardHeader>
              <div className="flex justify-between items-center">
                <CardTitle>Ocean Planet Learn</CardTitle>
                <div className="flex space-x-2">
                  <Button 
                    variant={viewMode === "lessons" ? "default" : "outline"} 
                    onClick={() => setViewMode("lessons")}
                  >
                    <BookOpen className="h-4 w-4 mr-2" />
                    Lessons
                  </Button>
                  <Button 
                    variant={viewMode === "quizzes" ? "default" : "outline"} 
                    onClick={() => setViewMode("quizzes")}
                  >
                    <Compass className="h-4 w-4 mr-2" />
                    Quizzes
                  </Button>
                  <Button 
                    variant={viewMode === "badges" ? "default" : "outline"} 
                    onClick={() => setViewMode("badges")}
                  >
                    <Award className="h-4 w-4 mr-2" />
                    Badges
                  </Button>
                </div>
              </div>
              <CardDescription>
                Short, interactive lessons about marine ecosystems and conservation
              </CardDescription>
            </CardHeader>
          </Card>
          
          {viewMode === "lessons" && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
              {filteredLessons.map(lesson => (
                <div key={lesson.id} onClick={() => handleLessonClick(lesson)}>
                  <LessonCard lesson={lesson} />
                </div>
              ))}
            </div>
          )}
          
          {viewMode === "quizzes" && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {filteredQuizzes.map(quiz => (
                <QuizCard key={quiz.id} quiz={quiz} />
              ))}
            </div>
          )}
          
          {viewMode === "badges" && (
            <BadgeDisplay badges={badges} />
          )}
        </div>
      </div>
    </div>
  );
}