import React, { useState } from "react";
import { useRoute } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { LessonViewer, Lesson } from "@/components/learn/LessonCard";
import { ChevronLeft, ChevronRight } from "lucide-react";

// This would normally come from an API, but for demo purposes we'll use static data
const lessons = [
  {
    id: 1,
    title: "Introduction to Coral Reefs",
    category: "reef-ecology",
    duration: 5,
    thumbnail: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Learn about the formation and importance of coral reefs in marine ecosystems.",
    completed: false,
    content: [
      {
        type: "text",
        data: "Coral reefs are underwater ecosystems characterized by reef-building corals. Reefs are formed of colonies of coral polyps held together by calcium carbonate. Most coral reefs are built from stony corals, whose polyps cluster in groups."
      },
      {
        type: "image",
        data: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        caption: "Vibrant coral reef with diverse marine life"
      },
      {
        type: "text",
        data: "Coral reefs are among the most diverse ecosystems on Earth, housing thousands of species of marine life. They provide habitat, breeding grounds, and protection for countless marine organisms."
      },
      {
        type: "funFact",
        data: "Although coral reefs cover less than 1% of the ocean floor, they support about 25% of all marine species!"
      }
    ]
  },
  {
    id: 2,
    title: "Understanding Ocean Currents",
    category: "ocean-literacy",
    duration: 3,
    thumbnail: "https://images.unsplash.com/photo-1566024287286-457247b70310?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
    description: "Discover how ocean currents shape marine environments and global climate.",
    completed: false,
    content: [
      {
        type: "text",
        data: "Ocean currents are continuous, directed movements of seawater generated by a number of forces acting upon the water, including wind, the Coriolis effect, temperature and salinity differences."
      },
      {
        type: "image",
        data: "https://images.unsplash.com/photo-1566024287286-457247b70310?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
        caption: "Ocean surface showing current patterns"
      },
      {
        type: "text",
        data: "Surface currents are primarily driven by winds. Deep ocean currents are driven by differences in water density, caused by variations in temperature and salinity - a process known as thermohaline circulation."
      },
      {
        type: "funFact",
        data: "The Gulf Stream transports nearly 4 billion cubic feet of water per second, which is more than 300 times the flow of the Amazon River!"
      }
    ]
  }
];

export default function LessonDetailPage() {
  const [match, params] = useRoute<{ id: string }>("/learn/lesson/:id");
  const lessonId = parseInt(params?.id || "1");
  
  // Find the current lesson
  const currentLesson = lessons.find(lesson => lesson.id === lessonId) || lessons[0];
  const currentIndex = lessons.findIndex(lesson => lesson.id === lessonId);
  
  // For navigation between lessons
  const prevLesson = currentIndex > 0 ? lessons[currentIndex - 1] : null;
  const nextLesson = currentIndex < lessons.length - 1 ? lessons[currentIndex + 1] : null;
  
  // For the swipeable lesson content (simplified version)
  const [currentPage, setCurrentPage] = useState(0);
  const totalPages = currentLesson.content.length;
  
  const nextPage = () => {
    if (currentPage < totalPages - 1) {
      setCurrentPage(currentPage + 1);
    }
  };
  
  const prevPage = () => {
    if (currentPage > 0) {
      setCurrentPage(currentPage - 1);
    }
  };
  
  // For marking lesson as complete
  const [isComplete, setIsComplete] = useState(currentLesson.completed);
  
  const markAsComplete = () => {
    // This would normally be an API call
    setIsComplete(true);
  };

  return (
    <div className="container py-6 mx-auto max-w-5xl">
      <div className="mb-6 flex justify-between items-center">
        <Button variant="outline" className="flex items-center" asChild>
          <a href="/learn">
            <ChevronLeft className="mr-2 h-4 w-4" />
            Back to Lessons
          </a>
        </Button>
        
        <div className="flex gap-2">
          <Badge variant="outline" className="bg-[#E0F7FA] text-[#0A4D68]">
            {currentLesson.category === "ocean-literacy" && "Ocean Literacy"}
            {currentLesson.category === "reef-ecology" && "Reef Ecology"}
            {currentLesson.category === "species-identification" && "Species ID"}
          </Badge>
          
          {isComplete ? (
            <Badge variant="outline" className="bg-green-100 text-green-800">
              Completed
            </Badge>
          ) : (
            <Badge variant="outline" className="bg-gray-100 text-gray-800">
              In Progress
            </Badge>
          )}
        </div>
      </div>
      
      {/* Main Lesson Content */}
      <Card className="mb-6">
        <CardContent className="p-0">
          {/* Swipeable lesson content - simplified version */}
          <div className="relative">
            <div className="p-6">
              {currentLesson.content[currentPage].type === "text" ? (
                <p className="text-gray-700 leading-relaxed">
                  {currentLesson.content[currentPage].data}
                </p>
              ) : currentLesson.content[currentPage].type === "image" ? (
                <div>
                  <img 
                    src={currentLesson.content[currentPage].data} 
                    alt={currentLesson.content[currentPage].caption || ""} 
                    className="w-full h-auto rounded-lg"
                  />
                  {currentLesson.content[currentPage].caption && (
                    <p className="text-sm text-gray-500 italic mt-2 text-center">
                      {currentLesson.content[currentPage].caption}
                    </p>
                  )}
                </div>
              ) : currentLesson.content[currentPage].type === "funFact" ? (
                <div className="bg-[#E0F7FA] p-4 rounded-lg border border-[#05BFDB]">
                  <h4 className="font-bold text-[#0A4D68] mb-1">Fun Fact</h4>
                  <p className="text-[#088395]">{currentLesson.content[currentPage].data}</p>
                </div>
              ) : null}
            </div>
            
            {/* Navigation controls */}
            <div className="flex justify-between p-4 border-t">
              <Button 
                variant="outline" 
                onClick={prevPage}
                disabled={currentPage === 0}
              >
                <ChevronLeft className="mr-2 h-4 w-4" />
                Previous
              </Button>
              
              <div className="flex items-center">
                <span className="text-sm text-gray-500">
                  {currentPage + 1} of {totalPages}
                </span>
              </div>
              
              {currentPage < totalPages - 1 ? (
                <Button 
                  className="bg-[#05BFDB] hover:bg-[#088395]"
                  onClick={nextPage}
                >
                  Next
                  <ChevronRight className="ml-2 h-4 w-4" />
                </Button>
              ) : (
                <Button 
                  className="bg-[#0A4D68] hover:bg-[#088395]"
                  onClick={markAsComplete}
                  disabled={isComplete}
                >
                  {isComplete ? "Completed" : "Mark as Complete"}
                </Button>
              )}
            </div>
          </div>
        </CardContent>
      </Card>
      
      {/* Next Up / Related Lessons */}
      <div className="mb-6">
        <h3 className="text-lg font-semibold mb-3">Continue Learning</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {prevLesson && (
            <Card className="flex hover:shadow-md transition-all">
              <div className="w-1/3">
                <img 
                  src={prevLesson.thumbnail} 
                  alt={prevLesson.title} 
                  className="h-full w-full object-cover"
                />
              </div>
              <div className="w-2/3 p-4">
                <h4 className="font-medium mb-1">{prevLesson.title}</h4>
                <p className="text-sm text-gray-600 mb-2 line-clamp-2">{prevLesson.description}</p>
                <Button variant="outline" size="sm" asChild>
                  <a href={`/learn/lesson/${prevLesson.id}`}>
                    <ChevronLeft className="mr-1 h-3 w-3" />
                    Previous Lesson
                  </a>
                </Button>
              </div>
            </Card>
          )}
          
          {nextLesson && (
            <Card className="flex hover:shadow-md transition-all">
              <div className="w-1/3">
                <img 
                  src={nextLesson.thumbnail} 
                  alt={nextLesson.title} 
                  className="h-full w-full object-cover"
                />
              </div>
              <div className="w-2/3 p-4">
                <h4 className="font-medium mb-1">{nextLesson.title}</h4>
                <p className="text-sm text-gray-600 mb-2 line-clamp-2">{nextLesson.description}</p>
                <Button variant="outline" size="sm" className="ml-auto" asChild>
                  <a href={`/learn/lesson/${nextLesson.id}`}>
                    Next Lesson
                    <ChevronRight className="ml-1 h-3 w-3" />
                  </a>
                </Button>
              </div>
            </Card>
          )}
        </div>
      </div>
      
      {/* Quiz Section */}
      <Card className="mb-6 bg-[#E0F7FA]">
        <CardContent className="p-6">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div>
              <h3 className="text-lg font-semibold text-[#0A4D68]">Test Your Knowledge</h3>
              <p className="text-[#088395]">Ready to see what you've learned about {currentLesson.title.toLowerCase()}?</p>
            </div>
            <Button className="mt-4 md:mt-0 bg-[#0A4D68] hover:bg-[#088395]">
              Take Quiz
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}