export interface LessonContent {
  type: 'text' | 'image' | 'funFact' | 'quiz';
  title?: string;
  content: string;
  image?: string;
  caption?: string;
  options?: string[];
  correctAnswer?: number;
  explanation?: string;
}

export interface Lesson {
  id: string;
  title: string;
  description: string;
  category: string;
  duration: number; // in minutes
  thumbnail: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  steps: LessonContent[];
}

export const lessons: Lesson[] = [
  {
    id: 'ocean-currents',
    title: 'Understanding Ocean Currents',
    description: 'Discover how ocean currents form, move around our planet, and influence climate, marine life, and human activities.',
    category: 'Ocean Literacy',
    duration: 5,
    thumbnail: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop&crop=entropy&auto=format',
    difficulty: 'Beginner',
    steps: [
      {
        type: 'text',
        title: 'What Are Ocean Currents?',
        content: `Ocean currents are continuous, directed movements of seawater generated by forces acting upon the water. Think of them as rivers flowing through the ocean.

These massive streams of water can be thousands of kilometers long and play a crucial role in distributing heat, nutrients, and marine life around our planet.

There are two main types of ocean currents:
• Surface currents - driven by wind and affecting the top 400 meters
• Deep water currents - driven by differences in water density`
      },
      {
        type: 'image',
        title: 'Global Ocean Current Patterns',
        content: 'This satellite image shows the major ocean current systems around the world. Notice how they form large circular patterns called gyres.',
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop&crop=entropy&auto=format',
        caption: 'Global ocean circulation patterns visualized through satellite data'
      },
      {
        type: 'text',
        title: 'How Ocean Currents Form',
        content: `Ocean currents are created by several key forces working together:

**Wind Power**: Trade winds and westerlies push surface water, creating the major current systems we see today.

**Coriolis Effect**: Earth's rotation deflects moving water to the right in the Northern Hemisphere and left in the Southern Hemisphere.

**Density Differences**: Cold, salty water is denser and sinks, while warm, less salty water rises, creating vertical circulation.

**Landmass Barriers**: Continents redirect currents, creating the circular gyre patterns in ocean basins.`
      },
      {
        type: 'funFact',
        title: 'Did You Know?',
        content: 'The Gulf Stream current is so powerful it transports 30 times more water than all the world\'s rivers combined! It moves at speeds up to 2.5 meters per second and carries warm water from the Gulf of Mexico all the way to Europe, keeping countries like the UK much warmer than they would otherwise be.'
      },
      {
        type: 'quiz',
        title: 'Test Your Knowledge',
        content: 'Which force is primarily responsible for creating the circular patterns (gyres) we see in ocean currents?',
        options: [
          'The gravitational pull of the moon',
          'The Coriolis effect from Earth\'s rotation',
          'Underwater volcanic activity',
          'The magnetic field of the Earth'
        ],
        correctAnswer: 1,
        explanation: 'The Coriolis effect, caused by Earth\'s rotation, deflects moving water and creates the characteristic circular gyre patterns in ocean basins. This is why currents curve clockwise in the Northern Hemisphere and counterclockwise in the Southern Hemisphere.'
      },
      {
        type: 'text',
        title: 'Why Ocean Currents Matter',
        content: `Ocean currents are essential for life on Earth and human civilization:

**Climate Regulation**: Currents transport heat from the equator to the poles, moderating global temperatures and weather patterns.

**Marine Ecosystems**: Nutrients carried by currents support marine food chains and determine where marine life thrives.

**Human Navigation**: For centuries, sailors have used currents to speed their journeys and save fuel.

**Carbon Cycle**: Currents help distribute carbon dioxide and oxygen throughout the ocean, affecting global climate.

Understanding ocean currents helps us predict weather, protect marine life, and navigate our changing planet.`
      }
    ]
  },
  {
    id: 'leeuwin-current',
    title: 'The Leeuwin Current: Australia\'s Unique Flow',
    description: 'Explore the Leeuwin Current, Western Australia\'s distinctive warm-water current that flows southward against prevailing winds.',
    category: 'Regional Oceanography',
    duration: 4,
    thumbnail: 'https://images.unsplash.com/photo-1582845512887-58e3c7936d86?w=800&h=600&fit=crop&crop=entropy&auto=format',
    difficulty: 'Intermediate',
    steps: [
      {
        type: 'text',
        title: 'Australia\'s Unusual Current',
        content: `The Leeuwin Current is one of the world's most unusual ocean currents. Unlike most eastern boundary currents that flow toward the equator with cold water, the Leeuwin Current flows southward along Western Australia's coast carrying warm, tropical water.

This unique current creates a marine environment unlike anywhere else on Earth, supporting tropical species far south of where they would normally be found.`
      },
      {
        type: 'image',
        title: 'Leeuwin Current Path',
        content: 'The Leeuwin Current flows from northwest to southwest along the Western Australian coast, bringing warm waters from the tropics.',
        image: 'https://images.unsplash.com/photo-1582845512887-58e3c7936d86?w=800&h=600&fit=crop&crop=entropy&auto=format',
        caption: 'Satellite imagery showing the warm Leeuwin Current flowing southward'
      },
      {
        type: 'funFact',
        title: 'Marine Highway',
        content: 'The Leeuwin Current acts as a "marine highway" for tropical fish larvae, carrying them thousands of kilometers south. This is why you can find tropical fish species like angelfish and butterflyfish in temperate waters around Perth and even as far south as Albany!'
      },
      {
        type: 'quiz',
        title: 'Quick Check',
        content: 'What makes the Leeuwin Current unique compared to other eastern boundary currents?',
        options: [
          'It flows northward with cold water',
          'It flows southward with warm water',
          'It only flows during summer months',
          'It changes direction with the tides'
        ],
        correctAnswer: 1,
        explanation: 'The Leeuwin Current is unique because it flows southward carrying warm, tropical water. Most other eastern boundary currents (like the California Current) flow toward the equator with cold water.'
      },
      {
        type: 'text',
        title: 'Impact on Marine Life and Diving',
        content: `The Leeuwin Current creates exceptional diving conditions along Western Australia:

**Biodiversity Hotspot**: The mixing of tropical and temperate waters creates incredibly diverse marine ecosystems.

**Seasonal Variations**: The current strengthens in winter, bringing clearer water and better visibility for diving.

**Unique Species**: Divers can encounter tropical species alongside temperate ones in the same dive.

**Coral Reefs**: The warm water supports the world's southernmost coral reefs at places like Rottnest Island.

Understanding the Leeuwin Current helps divers choose the best times and locations for exploring Western Australia's underwater treasures.`
      }
    ]
  }
];

export const getLessonById = (id: string): Lesson | undefined => {
  return lessons.find(lesson => lesson.id === id);
};